version: '3'
services:
    test_nginx:
        build:
            context: ./.docker/nginx
            dockerfile: Dockerfile
        container_name: urlcut_service_nginx
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./:/var/www/
            - ./var:/var/www/var
            - ./vendor:/var/www/vendor
        links:
            - test_php
        networks:
            - urlcutservice_network


    test_php:
        build: ./.docker/php
        container_name: urlcut_service_php
        links:
            - test_mysql
        volumes:
            - ./:/var/www
        networks:
            - urlcutservice_network

    test_mysql:
        image: mysql:latest
        container_name: urlcut_service_db
        volumes:
           - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
           - ./.docker/mysql/logs/:/var/log/mysql
        environment:
            MYSQL_HOST: urlcutservice_db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: url_shortener
            MYSQL_USER: user
            MYSQL_PASSWORD: user
        ports:
            - "${DB_PORT}:3306"
        networks:
            - urlcutservice_network
networks:
    urlcutservice_network:
        driver: bridge
